name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  tests:
    uses: ./.github/workflows/testing.yml
    with:
      should-release: true

  goreleaser:
    needs: tests
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
